[Interface]
PrivateKey = yL0hKUoNVsMaTrr2addSJDOAhhx281QYpsQlHhslPno=
Address = 10.10.0.2/32

[Peer]
PublicKey = e2AwC1S8OcsmU5ZnBvIrfaulfG6Cgep4XI9SwVgXeCA=
AllowedIPs = 10.10.0.0/24
Endpoint = 192.168.1.235:51088
PersistentKeepalive = 25
