[Interface]
PrivateKey = +PXcJMM9NqZNyPEa1zRUZULsTe1IvuS6PhU8M+b+WE0=
Address = 10.191.1.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = LlKV5NZZA5I+8UxaaDuN1LZTHS1R1vGl2RjnCBC0P3k=
PresharedKey = UhcfP8qMkI3KZEbwtBTkQR1t6gLgOg/tM+O+bsWlgd0=
AllowedIPs = 0.0.0.0/0
Endpoint = 192.168.1.111:51820
PersistentKeepalive = 25
